spring.application.name=ecole

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/lycee2
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymleaf - DÉSACTIVE LE CACHE
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

# Devtools pour rechargement automatique
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Logging
logging.level.org.springframework.boot=INFO