spring.application.name=ecole

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/lycee2
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration - CRUCIAL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Désactiver complètement la validation du schéma
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.generate-ddl=false
spring.jpa.hibernate.use-new-id-generator-mappings=false

# Logging
logging.level.org.hibernate=ERROR
logging.level.org.springframework.boot=INFO

# Thymleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html